name: CI
on: [push]
jobs:
  test_build_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run : |
          pip install pytest
          pytest
      - name: build docker image
        run :
          docker build -t ynov_lyon .
      - name: run docker image
        run :
          docker run ynov_lyon
      - name: docker login
        env: 
          USERNAME: ${{secrets.DOCKER_USERNAME}}
          PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run :
          doker login -u $USERNAME -p $PASSWORD